channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - netcdf4
  - intake
  - intake-xarray
  - datashader
  - geoviews
  - hvplot  
  - panel
  - fsspec
  - s3fs
  - cf-time
  - pyproj
  - zarr
