channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - xarray
  - netcdf4
  - intake
  - intake-xarray
  - bokeh  
  - datashader
  - holoviews=1.12.1 
  - geoviews
  - hvplot  
  - panel
