channels:
  - conda-forge
dependencies:
  - cartopy
  - xarray
  - netcdf4
  - intake
  - intake-xarray
  - bokeh  
  - datashader
  - holoviews
  - geoviews
  - hvplot  
  - panel
  - fsspec
  - s3fs
